server.port: 9090
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ebanking
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://desktop-o2f3aut:8080/realms/ILV #http://localhost:8080/realms/ILV
server:
  error:
    include-message: always